### ISSUE TITLE
Close toolbar confirmation popup shold have Cancel option

### ISSUE THREAD

**Issue by huytd** [vimdotmd/vimdotmd#1]
**Describe the bug**
When I clicked on Close Toolbar button because I want to know what is that button, I got the message tell me how to re-enabled it again. At this phase, I almost freak out and just want to cancel this action. But there's no way to do so.

<img width="633" alt="image" src="https://user-images.githubusercontent.com/613943/93855135-dbf22080-fc6b-11ea-8148-53e564b5e5e2.png">

**To Reproduce**
1. Click on Close Toolbar button
2. See the popup messsage
3. Freak out

**Expected behavior**
Should have the Cancel button to cancel the close action.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: All OS
 - Browser: All Browser
 - Version: As if I know it

**Comment by thien-do** [comment]
Invalid because of #10 

Thank anyway @huytd the history will forever remember you as the first issue creator in this repository
