### ISSUE TITLE
Have a button to show the toolbar back

### ISSUE THREAD

**Issue by thien-do** [vimdotmd/vimdotmd#10]
The toolbar hiding (via button) is the source of many feedback recently:
1. People don't read. Most of them don't know the toolbar should be activated back via `:t`
2. Even so, that's a sub-optimal experience because:
    - In preview mode, the user can't type command
    - It's not intuitive when the "show" and "hide" are being done via different mechanism
    - It won't work in non-vim deployment, if we do

So the solution should be having a permanent button on the top to show the toolbar back.

I think it's acceptable because all other functionalities can be accessed via the toolbar. I believe this is worth as the only exception.

**Comment by iamquang95** [comment]
Haven't released yet

**Comment by thien-do** [comment]
The fix is released to [vim.md](https://vim.md)! For a full list of changes please see the [release detail](https://github.com/vimdotmd/vimdotmd/projects/1#column-10970008).
