### ISSUE TITLE
Avoid conflicting with original vim command

### ISSUE THREAD

**Issue by thien-do** [vimdotmd/vimdotmd#11]
- `:s` is for substitute. Should not use for Split mode. Split mode should be `:sp[lit]` I think
- `:e` is for edit (open) a new file. Editor mode should use `:ed[itor]`?

**Comment by thien-do** [comment]
@iamquang95 should we bind `:e` to the library to have autocomplete?

**Comment by iamquang95** [comment]
:e should open lib or maybe :e .
We may want to support `:e <path>`

**Comment by thien-do** [comment]
The fix is released to [vim.md](https://vim.md)! For a full list of changes please see the [release detail](https://github.com/vimdotmd/vimdotmd/projects/1#column-10970008).
