### ISSUE TITLE
Better showing duplicated file name

### ISSUE THREAD

**Issue by iamquang95** [vimdotmd/vimdotmd#15]
**I tried this:**

![image](https://user-images.githubusercontent.com/8794293/94181264-6b483f80-fec9-11ea-8135-13484d8c2820.png)
**I expected to see this happen:** duplicate file name

**Comment by thien-do** [comment]
Is 422 always mean "duplicate file name" or should we check it client-side?

**Comment by thien-do** [comment]
Fixed and released in [1.2](https://github.com/vimdotmd/vimdotmd/projects/1#column-11066642) :tada:
