### ISSUE TITLE
Better link color in dark mode

### ISSUE THREAD

**Issue by iamquang95** [vimdotmd/vimdotmd#16]
![image](https://user-images.githubusercontent.com/8794293/94181938-6a63dd80-feca-11ea-8cbb-c4954c34ce3b.png)

Well, as title

**Comment by thien-do** [comment]
Hey guys the fix is released to [vim.md](https://vim.md)! For a full list of changes please see the [release detail](https://github.com/vimdotmd/vimdotmd/projects/1#column-10970008).
