### ISSUE TITLE
Losing unsaved note when switch repo

### ISSUE THREAD

**Issue by huytd** [vimdotmd/vimdotmd#17]
**I tried this:**
1. Write a note
2. Do not save it yet
3. Switch to another repository
4. Boom, the editor cleared, where's my WIP note?

**I expected to see this happen:**
It should either warn me about losing WIP notes or cache the note content in the browser.

**Instead, this happened:**
Losing my WIP notes without any warning

**Comment by thien-do** [comment]
Fixed and released in [1.2](https://github.com/vimdotmd/vimdotmd/projects/1#column-11066642) :tada:
