### ISSUE TITLE
Option to set tab width and use spaces as tab

### ISSUE THREAD

**Issue by huytd** [vimdotmd/vimdotmd#19]
**I tried this:**
1. Press tab
2. Feeling gross

**I expected to see this happen:**
For now, the editor use a single `\t` as tab. I know many people prefer this but my personal preference is either 2 spaces or 4 spaces instead of a single `\t`.

There should be an option in Preferences that let users use Space or Tab characters as Tab, and also, let them configure the tab width.

**Comment by thien-do** [comment]
Thank you. I totally agree! There is already an issue for this in our private repo. We will prioritize this! You can expect to see it lands in the next minor release

**Comment by thien-do** [comment]
Hey @huytd just want to say thank. This turns out to be a much more interested problem than I thought :+1: 
https://github.com/codemirror/CodeMirror/issues/106
https://github.com/codemirror/CodeMirror/issues/988

**Comment by huytd** [comment]
That sounds great

**Comment by thien-do** [comment]
Added and released in [1.2](https://github.com/vimdotmd/vimdotmd/projects/1#column-11066642) :tada:
