### ISSUE TITLE
Editor loading forever when changing repo

### ISSUE THREAD

**Issue by iamquang95** [vimdotmd/vimdotmd#20]
**I tried this:**
1. View a file
2. Change to another repo
![image](https://user-images.githubusercontent.com/8794293/94462800-3ea46880-01e6-11eb-80a9-7326b9fc6149.png)

**I expected to see this happen:** New empty doc

**Comment by thien-do** [comment]
Fixed and released in [1.2](https://github.com/vimdotmd/vimdotmd/projects/1#column-11066642) :tada:
