### ISSUE TITLE
Unnecessary alert when nothing to save

### ISSUE THREAD

**Issue by huytd** [vimdotmd/vimdotmd#22]
As a good old habit, I tend to hit save a lot.

**I tried this:**
1. Save the document
2. Save again

**I expected to see this happen:**
If nothing need to be saved again, there's no need to display the alert popup. We can just ignore it.

**Instead, this happened:**
This popup showup:
<img width="346" alt="image" src="https://user-images.githubusercontent.com/613943/94855463-66145480-03e3-11eb-911e-a5d9845e4341.png">

**Comment by thien-do** [comment]
Yeah I agree it's annoying. The current implementation even prevent saving an empty file. We will fix this.

**Comment by thien-do** [comment]
Hi @huytd , we have fixed the behavior. Now you can save an empty document and ":w" when there is nothing changes won't throw error

![Screenshot from 2020-11-11 08-11-07](https://user-images.githubusercontent.com/5953369/98752797-84636c00-23f5-11eb-9e11-8e53e355dc16.png)
