### ISSUE TITLE
Allow scroll sync on `split` view mode.

### ISSUE THREAD

**Issue by frangte** [vimdotmd/vimdotmd#28]
**I'd like Vim.md to have:**
- Like title.

**It is necessary because:**
- With a huge document `scroll sync` is very useful, is make me focus on typing and don't need to scroll through each one separately to find where is cursor.

Thanks!

**Comment by thien-do** [comment]
Hi @frangte thanks for the feedback. Just want to make sure if we understand you correctly. Currently vim.md will scroll the Preview pane (on the right side) following your cursor in the Editor pane (on the left side), so:
1. Is the Preview pane scroll itself correctly following your cursor in the Editor?
2. Or do you want us to scroll the Editor when you scroll the Preview?

Vim.md is currently using a minimum-effort approach in scrolling the Preview, in the mean that it only scrolls if the current line is out of view and will scroll as less as possible to move it into viewport.

**Comment by thien-do** [comment]
Hi, I'm closing the issue due to no reply. Feel free to re-open it otherwise
