### ISSUE TITLE
Can not Sign in with Safari

### ISSUE THREAD

**Issue by xuanvan229** [vimdotmd/vimdotmd#3]
**Describe the bug**
Can not Sign in with Safari

**To Reproduce**
1. Open with Safari
2. Click on 'Sign in with Github'
4. See an error

**Expected behavior**
Sign in with Safari

**Screenshots**
<img width="417" alt="Screen Shot 2020-09-22 at 3 23 42 PM" src="https://user-images.githubusercontent.com/22408713/93860481-5dd45f00-fce9-11ea-9c47-eede7c4245ad.png">

**Desktop (please complete the following information):**
 - OS: MacOS 10.14
 - Browser : Safari
 - Version : 13.0.2

**Additional context**
N/A

**Comment by iamquang95** [comment]
I can't re-procedure. I can guess that you were trying to login when we hadn't nuked the users database.
Maybe can you try to clear your local storage and try to login again.

**Comment by thien-do** [comment]
@xuanvan229 look like it's fixed in [1.2](https://github.com/vimdotmd/vimdotmd/projects/1#column-11066642) :tada: Please feel free to re-open the issue if it's not
