### ISSUE TITLE
As user I can create a list of checkbox

### ISSUE THREAD

**Issue by namtx** [vimdotmd/vimdotmd#30]
Currently, user can NOT create a list of checkbox
<img width="1428" alt="vim_md" src="https://user-images.githubusercontent.com/25602820/95279183-4023ff80-087c-11eb-8653-7c37499e8662.png">

As a User, I want to create a list of toggable checkbox like:
- [ ] [Github](https://github.com/)
- [x] [Google](https://google.com/)

**Comment by thien-do** [comment]
Ah yes... sorry about that. We will try to show the checkbox properly first, and then add the toggle-ability and re-ordering later :D 

We will keep you update here!

**Comment by thien-do** [comment]
Check boxes are now rendered:

![Screenshot from 2020-11-11 08-03-52](https://user-images.githubusercontent.com/5953369/98752284-782adf00-23f4-11eb-808b-e9c30b30dc23.png)

**Comment by namtx** [comment]
great!

**Comment by thien-do** [comment]
Oh you are fast!

Because of that we will try to make the check boxes interactive (i.e. you can click on it in the preview) in the next release!
