### ISSUE TITLE
Emoji color hurt my eyes

### ISSUE THREAD

**Issue by ZeroX-DG** [vimdotmd/vimdotmd#31]
Please help, my OCD won't let me live with this :sob: 

![image](https://user-images.githubusercontent.com/12984316/95650172-5234c500-0b3e-11eb-8590-79d75b97e255.png)

**Comment by thien-do** [comment]
Hi @ZeroX-DG , this is fixed:

![Screenshot from 2020-11-11 08-08-01](https://user-images.githubusercontent.com/5953369/98752563-08692400-23f5-11eb-91f0-e8ae5542c917.png)
