### ISSUE TITLE
Add command :wq

### ISSUE THREAD

**Issue by xuanvan229** [vimdotmd/vimdotmd#4]
**Is your feature request related to a problem? Please describe.**
Many of vim's users using this command when using vim `:wq`. I think we need add `:wq`. Because when I want to save and quit. I type 2 times for this. 

**Describe the solution you'd like**
Add command `:wq` for save and quit

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by thien-do** [comment]
Hey @xuanvan229 the fix is released to [vim.md](https://vim.md)! For a full list of changes please see the [release detail](https://github.com/vimdotmd/vimdotmd/projects/1#column-10970008).
