### ISSUE TITLE
Possible XSS when having sharable link

### ISSUE THREAD

**Issue by iamquang95** [vimdotmd/vimdotmd#5]
**Describe the bug**
Add a script to a document, then using "share file" feature. When user open that file on vim.md, there is possible a XSS happens.

It's really serious when having sharing file feature. 

**Additional context**

**Comment by iamquang95** [comment]
Haven't released yet

**Comment by thien-do** [comment]
Hey guys the fix is released to [vim.md](https://vim.md)! For a full list of changes please see the [release detail](https://github.com/vimdotmd/vimdotmd/projects/1#column-10970008).
