### ISSUE TITLE
Custom CSS for previewer

### ISSUE THREAD

**Issue by ZeroX-DG** [vimdotmd/vimdotmd#8]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when the previewer looks a bit plain. I want the previewer to be worthy of the beauty of the app UI/UX.

**Describe the solution you'd like**
A clear and concise description of what I want to happen is to be able to add custom CSS for the previewer.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features I've considered is: 
- Style preset: Having a list of supported markdown styles that looks cool. Hand-made themes just for vimdotmd. Not very satisfying but would be a big plus.

**Additional context**
With custom CSS, I can make awesome looks for the previewer.

| Before | After |
|----|---|
| ![image](https://user-images.githubusercontent.com/12984316/93962209-5d51cc00-fdae-11ea-91f3-c421fa19222f.png) | ![image](https://user-images.githubusercontent.com/12984316/93962137-2aa7d380-fdae-11ea-9acb-32b9d5bb1412.png) |

**Comment by thien-do** [comment]
We will definitely have this! For your information, there is already a hidden setting called "Preview Template" for this exact purpose :D We pay a lot of effort to the current GitHub-like template, but surely it won't be the only one.

We will have a serif or slab one soon, which are optimized for book-like feeling

We will look into the option of custom CSS right after that

**Comment by thien-do** [comment]
Hi @ZeroX-DG @xuanvan229 this has been done in the latest release!

![Screenshot from 2020-11-11 08-20-22](https://user-images.githubusercontent.com/5953369/98753369-c2ad5b00-23f6-11eb-822c-6ca4752b95da.png)


Please note that the "Serif" template is still pretty basic and we are still working actively to improve it! Just want to share it asap
