### ISSUE TITLE
Delete button icon is unclear

### ISSUE THREAD

**Issue by ZeroX-DG** [vimdotmd/vimdotmd#9]
**Describe the bug**
Not really a bug but I find the icon next to the file is a bit unclear. At first I thought it was to ignore the file from file list so it get less distracting, but then I realized it actually remove the file from the repo, which is pretty dangerous consider that it doesn't even show a confirm dialog or anything.

**To Reproduce**
1. Go to app
2. Open library
3. Click on the `x` icon next to the file
4. Cry a lot cus it remove a document that you spent your youth typing it.

**Expected behavior**
A clear and concise description of what the icon expected to do. Plus a confirm dialog if possible.

**Screenshots**
![image](https://user-images.githubusercontent.com/12984316/93975422-8af93e00-fdcb-11ea-9555-44351887fd1e.png)

**Comment by thien-do** [comment]
Sorry for the unclear behavior. We will change it to the Trash icon I think

> It doesn't even show a confirm dialog or anything.

This sounds like a bug. It should show a confirmation

> Cry a lot cus it remove a document that you spent your youth typing it.

Don't worry, it's git-based so you'll never lost your document :D you can still see it in the commit history in GitHub for example

**Comment by thien-do** [comment]
Ok I've just checked and confirm there is a bug that prevent the confirmation popup from showing. Will fix now

**Comment by iamquang95** [comment]
Haven't released yet

**Comment by thien-do** [comment]
Hey guys the fix is released to [vim.md](https://vim.md)! For a full list of changes please see the [release detail](https://github.com/vimdotmd/vimdotmd/projects/1#column-10970008).

**Comment by thien-do** [comment]
cc @ptgamr
